### ISSUE TITLE
Secondary #b6ada5 "show shades" button does not expand subsection

### ISSUE THREAD

**Issue by BillCChang** [tietgenlabs/branding#80]
## Area

The bottom of the Colors page.   Supporting Color Palette section

## Context

Secondary #b6ada5 "show shades" button does not expand subsection

## Value

I assume it should expand.

## Steps to Reproduce

Click on "show shades"

## Supporting Information

![image](https://cloud.githubusercontent.com/assets/12704007/21732213/15632410-d41e-11e6-97f0-2c329c7f5fe6.png)

**Comment by tomkersten** [comment]
@BillCChang this has been fixed, but I am not sure when...it might have been a by-product of the view refactor @petebot just did.
